### ISSUE TITLE
LIST-S2 HTML interface - request to add Cancel Job function

### ISSUE THREAD

**Issue by alptaciroglu** [NawarMalhis/LIST-S2#2]
I would appreciate if you could add 'Cancel Job' function. I added some jobs with wrong input type (thinking of Multiple sequence alignments instead) and now worried about swarming the servers. 
Thanks for your work

**Comment by NawarMalhis** [comment]
Hi Alperen,

There is a delete button at the left most of each line.

Best regards,

Nawar

**Comment by alptaciroglu** [comment]
Well this is embarrassing
